#SPDX-License-Identifier: MIT-0
---
# tasks file for httpdtest

- name: apache httpd Action
  ansible.builtin.apt:
    name: apache2
    state: absent

- name: copy the index.html file to remote server
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'